;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2016/4/3 14:58:13

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1012	1012	; struts2 java\struts2\struts2-xml.htm
#define IDH_1005	1005	; webservice_axis java\接口协议\webservice_axis.htm
#define IDH_1028	1028	; http请求调用 java\接口协议\http请求调用.htm
#define IDH_1022	1022	; reflect java\reflect\reflect.htm
#define IDH_1013	1013	; parse java\parse\parse.htm
#define IDH_1027	1027	; 分流算法 java\算法\分流算法.htm
#define IDH_1044	1044	; log4j java\log4j\log4j.htm
#define IDH_1011	1011	; 创建Popup js\创建Popup.htm
#define IDH_1007	1007	; js知识一 js\jsknowledge-one.html
#define IDH_1023	1023	; js 知识2 js\jsknowledge-two.html
#define IDH_1024	1024	; json js\json.html
#define IDH_1025	1025	; js插件.html js\懒加载.html
#define IDH_1001	1001	; 基础ajax ajax\ajax.html
#define IDH_1000	1000	; juery_ajax ajax\jquery ajax.html
#define IDH_1002	1002	; DWR ajax\dwr.html
#define IDH_1017	1017	; oracle-tools oracle\oracle(一).htm
#define IDH_1029	1029	; oracle优化篇 oracle\oracle优化篇.html
#define IDH_1038	1038	; oracle工具篇 oracle\oracle工具篇.html
#define IDH_1039	1039	; oracle索引篇 oracle\oracle索引篇.html
#define IDH_1015	1015	; linux一 linux\linux(一).htm
#define IDH_1032	1032	; shell编程 linux\shell.htm
#define IDH_1051	1051	; hbase指令集 hadoop\hbase\hbase指令集.htm
#define IDH_1042	1042	; hbaseAPI hadoop\hbase\hbaseAPI.htm
#define IDH_1041	1041	; hbase原理 hadoop\hbase\hbase元数据.htm
#define IDH_1050	1050	; hbase优化 hadoop\hbase\hbase优化.htm
#define IDH_1036	1036	; hive-cli hadoop\hive\hive-cli.htm
#define IDH_1033	1033	; hive配置 hadoop\hive\hive配置.htm
#define IDH_1034	1034	; hive优化 hadoop\hive\hive优化.htm
#define IDH_1035	1035	; hive函数 hadoop\hive\hive函数.htm
#define IDH_1037	1037	; hive 自定义函数 hadoop\hive\hive自定义函数.htm
#define IDH_1048	1048	; zookeeper指令集 hadoop\zookeeper\zookeeper指令集.htm
#define IDH_1052	1052	; zookeeper优化 hadoop\zookeeper\zookeeper优化.htm
#define IDH_1047	1047	; kafka指令集 hadoop\kafka\kafka指令集.htm
#define IDH_1046	1046	; 指令集 hadoop\HDFS指令集.htm
#define IDH_1010	1010	; 技巧 工具\utils.htm
#define IDH_1020	1020	; tab选项卡 example\tab_example.htm
