;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2016/7/6 11:11:29

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1056	1056	; hadoop原理 hadoop\hadoop\hadoop原理.htm
#define IDH_1046	1046	; hadoop指令集 hadoop\hadoop\hadoop指令集.htm
#define IDH_1020	1020	; 调度器 hadoop\yarn\yarn调度.htm
#define IDH_1051	1051	; hbase指令集 hadoop\hbase\hbase指令集.htm
#define IDH_1042	1042	; hbaseAPI hadoop\hbase\hbaseAPI.htm
#define IDH_1041	1041	; hbase原理 hadoop\hbase\hbase元数据.htm
#define IDH_1050	1050	; hbase配置与优化 hadoop\hbase\hbase配置与优化.htm
#define IDH_1054	1054	; protocol hadoop\hbase\protocol buffer.htm
#define IDH_1036	1036	; hive-cli hadoop\hive\hive-cli.htm
#define IDH_1033	1033	; hive配置 hadoop\hive\hive配置.htm
#define IDH_1034	1034	; hive优化 hadoop\hive\hive优化.htm
#define IDH_1035	1035	; hive语法 hadoop\hive\hive语法.htm
#define IDH_1037	1037	; hive 自定义函数 hadoop\hive\hive自定义函数.htm
#define IDH_1048	1048	; zookeeper指令集 hadoop\zookeeper\zookeeper指令集.htm
#define IDH_1052	1052	; zookeeper优化 hadoop\zookeeper\zookeeper优化.htm
#define IDH_1047	1047	; kafka指令集 hadoop\kafka\kafka指令集.htm
#define IDH_1053	1053	; kafka配置与优化 hadoop\kafka\kafka配置与优化.htm
#define IDH_1063	1063	; 基本原理 java\jvm\基本原理.htm
#define IDH_1062	1062	; GC java\jvm\GC.htm
#define IDH_1028	1028	; http原生 java\http\http原生.htm
#define IDH_1005	1005	; axis java\http\axis.htm
#define IDH_1065	1065	; jersey java\http\jersey.htm
#define IDH_1044	1044	; log4j java\log4j\log4j.htm
#define IDH_1022	1022	; 反射 java\基础\反射.htm
#define IDH_1013	1013	; 解析 java\xml\解析.htm
#define IDH_1012	1012	; struts2 java\框架\struts2.htm
#define IDH_1024	1024	; json 前端\javascript\json.html
#define IDH_1007	1007	; js知识一 前端\javascript\jsknowledge-one.html
#define IDH_1023	1023	; js 知识2 前端\javascript\jsknowledge-two.html
#define IDH_1011	1011	; 创建Popup 前端\javascript\创建Popup.htm
#define IDH_1025	1025	; js插件.html 前端\javascript\懒加载.html
#define IDH_1001	1001	; 基础ajax 前端\ajax\ajax.html
#define IDH_1000	1000	; juery_ajax 前端\ajax\jquery ajax.html
#define IDH_1002	1002	; DWR 前端\ajax\dwr.html
#define IDH_1069	1069	; ember 前端\emberJS\ember.htm
#define IDH_1068	1068	; puppet ruby\puppet\puppet.htm
#define IDH_1017	1017	; oracle-tools 数据库\oracle\oracle(一).htm
#define IDH_1029	1029	; oracle优化篇 数据库\oracle\oracle优化篇.html
#define IDH_1038	1038	; oracle工具篇 数据库\oracle\oracle工具篇.html
#define IDH_1039	1039	; oracle索引篇 数据库\oracle\oracle索引篇.html
#define IDH_1060	1060	; oracle 数据库\mysql\mysql基础.htm
#define IDH_1015	1015	; linux命令 linux\linux命令.htm
#define IDH_1032	1032	; shell编程 linux\shell.htm
#define IDH_1027	1027	; 分流算法 算法\分流算法.htm
#define IDH_1010	1010	; 技巧 工具\utils.htm
