;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2016/2/17 15:03:52

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

IDH_1012=java\struts2\struts2-xml.htm	; struts2
IDH_1005=java\接口协议\webservice_axis.htm	; webservice_axis
IDH_1028=java\接口协议\http请求调用.htm	; http请求调用
IDH_1022=java\reflect\reflect.htm	; reflect
IDH_1013=java\parse\parse.htm	; parse
IDH_1027=java\算法\分流算法.htm	; 分流算法
IDH_1011=js\创建Popup.htm	; 创建Popup
IDH_1007=js\jsknowledge-one.html	; js知识一
IDH_1023=js\jsknowledge-two.html	; js 知识2
IDH_1024=js\json.html	; json
IDH_1025=js\懒加载.html	; js插件.html
IDH_1001=ajax\ajax.html	; 基础ajax
IDH_1000=ajax\jquery ajax.html	; juery_ajax
IDH_1002=ajax\dwr.html	; DWR
IDH_1017=oracle\oracle(一).htm	; oracle-tools
IDH_1029=oracle\oracle优化篇.html	; oracle优化篇
IDH_1038=oracle\oracle工具篇.html	; oracle工具篇
IDH_1039=oracle\oracle索引篇.html	; oracle索引篇
IDH_1015=linux\linux(一).htm	; linux一
IDH_1032=linux\shell.htm	; shell编程
IDH_1036=hadoop\hive\hive-cli.htm	; hive-cli
IDH_1033=hadoop\hive\hive配置.htm	; hive配置
IDH_1034=hadoop\hive\hive优化.htm	; hive优化
IDH_1035=hadoop\hive\hive函数.htm	; hive函数
IDH_1037=hadoop\hive\hive自定义函数.htm	; hive 自定义函数
IDH_1010=工具\utils.htm	; 技巧
IDH_1020=example\tab_example.htm	; tab选项卡
